### ISSUE TITLE
Validate access token occasionally

### ISSUE THREAD

**Issue by CMDRyan** [oursky/gitlab-cicd-dashboard#10]
Allowing to reach the dashboard without having to be redirected to gitlab authorization page every time they refresh

**Comment by CMDRyan** [comment]
Since the response does not include "expires_in" parameter.
Server has to check if the token is valid occasionally

**Comment by Steven-Chan** [comment]
@CMDRyan Server does not need to check "occasionally". You only need it to be valid when you use it.

In fact, the server does not really need to check it actively. When it calls Gitlab API with the access token, Gitlab will tell you if the token is valid.

What you need to do is to handle the error (when Gitlab tell you the token is invalid) correctly.

**Comment by CMDRyan** [comment]
replace this issue with new error handling issue
