### ISSUE TITLE
Check Token with initial link

### ISSUE THREAD

**Issue by CMDRyan** [oursky/gitlab-cicd-dashboard#13]
Requirement:
/groups/:id/jobs must check if user has already logged in or not, if not, redirect back to fetch token. otherwise straight to the dashboard

**Comment by CMDRyan** [comment]
@Steven-Chan 

- From Getting /groups/:id/jobs Request:

1. Pass access_code from cookie to query at the end -> ../jobs?access_code
2. If access_code in cookie does not exist or expired, redirect to login sequence
3. Once token is obtained, server set-cookie access code, and expires at (time now + 7200 sec)
4. go back to (1)

Just would like to make sure the idea is workable.

**Comment by Steven-Chan** [comment]
@CMDRyan 
What is access_code?

Any kind of tokens should not be put in the url query string, otherwise the security level will go down to OAuth 2.0 implicit grant, which is not suggested nowadays.

You need to understand how cookie work first.

**Comment by Steven-Chan** [comment]
@CMDRyan The title Check Token with _initial link_ looks like you understand the feature in a wrong way. If we have more than one pages that require user login, all of them need to check.

**Comment by CMDRyan** [comment]
@Steven-Chan 

1. Will create a spike task, trying to study how Cookie works.
2. From there, initiate a new plan on storing cookies, check and reading them
