### ISSUE TITLE
Create getCookie.js to parse cookie

### ISSUE THREAD

**Issue by CMDRyan** [oursky/gitlab-cicd-dashboard#15]
Cookies read as string by the server.
need to be parse and only read data (token)

**Comment by Steven-Chan** [comment]
@CMDRyan have you seen https://expressjs.com/en/resources/middleware/cookie-parser.html?

**Comment by CMDRyan** [comment]
@Steven-Chan Yes I have seen it, but trying not to install libraries.

**Comment by CMDRyan** [comment]
solved: split cookie, and take [1]
