### ISSUE TITLE
Obtain user IP from header for the time offset 

### ISSUE THREAD

**Issue by CMDRyan** [oursky/gitlab-cicd-dashboard#62]
Using the request's X-Forwarded-For header to get client ip.
From there get their location or time offset for client time conversion

**Comment by CMDRyan** [comment]
ipapi.co : 
30000 requests/month limit
1000/day limit

returns: "utc_offset": "",

**Comment by Steven-Chan** [comment]
There is one possible enhancement, which is to cache the timezone value with client IP.
